[package]
name = "processes_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1"
landlock = "0.4.1"
log = "0.4"
regex = { version = "1.11.0", default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
